"""initial schema

Revision ID: ed1dc6cf5238
Revises: 
Create Date: 2026-08-11 17:17:49.641727
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import caps_dash.db.types

revision: str = 'ed1dc6cf5238'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('floor', sa.String(length=16), nullable=False),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('source_url', sa.String(length=255), nullable=False),
    sa.Column('poll_interval_s', sa.Float(), nullable=False),
    sa.Column('vote_window', sa.Integer(), nullable=False),
    sa.Column('vote_threshold', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('frame_width', sa.Integer(), nullable=False),
    sa.Column('frame_height', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', caps_dash.db.types.UtcDateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('created_at', caps_dash.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', caps_dash.db.types.UtcDateTime(), nullable=False),
    sa.CheckConstraint("source_type IN ('esp32cam_http', 'image_folder', 'video_file', 'fake')", name=op.f('ck_cameras_source_type_valid')),
    sa.CheckConstraint('confidence > 0 AND confidence < 1', name=op.f('ck_cameras_confidence_in_range')),
    sa.CheckConstraint('poll_interval_s > 0', name=op.f('ck_cameras_poll_interval_positive')),
    sa.CheckConstraint('vote_threshold <= vote_window', name=op.f('ck_cameras_threshold_within_window')),
    sa.CheckConstraint('vote_window >= 1', name=op.f('ck_cameras_window_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cameras'))
    )
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cameras_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_cameras_floor'), ['floor'], unique=False)
        batch_op.create_index(batch_op.f('ix_cameras_is_enabled'), ['is_enabled'], unique=False)

    op.create_table('hourly_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=8), nullable=False),
    sa.Column('scope_key', sa.String(length=32), nullable=False),
    sa.Column('hour_start', caps_dash.db.types.UtcDateTime(), nullable=False),
    sa.Column('occupied_seconds', sa.Float(), nullable=False),
    sa.Column('free_seconds', sa.Float(), nullable=False),
    sa.Column('unknown_seconds', sa.Float(), nullable=False),
    sa.Column('change_count', sa.Integer(), nullable=False),
    sa.Column('peak_occupied', sa.Integer(), nullable=False),
    sa.Column('slot_count', sa.Integer(), nullable=False),
    sa.Column('clock_suspect', sa.Boolean(), nullable=False),
    sa.CheckConstraint("scope_type IN ('slot', 'floor', 'site')", name=op.f('ck_hourly_stats_scope_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hourly_stats')),
    sa.UniqueConstraint('scope_type', 'scope_key', 'hour_start', name='scope_hour_unique')
    )
    with op.batch_alter_table('hourly_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hourly_stats_clock_suspect'), ['clock_suspect'], unique=False)
        batch_op.create_index(batch_op.f('ix_hourly_stats_hour_start'), ['hour_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_hourly_stats_scope_key'), ['scope_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_hourly_stats_scope_type'), ['scope_type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('last_login_at', caps_dash.db.types.UtcDateTime(), nullable=True),
    sa.Column('created_at', caps_dash.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', caps_dash.db.types.UtcDateTime(), nullable=False),
    sa.CheckConstraint("role IN ('resident', 'security', 'admin')", name=op.f('ck_users_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('entity_type', sa.String(length=24), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('message_code', sa.String(length=64), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', caps_dash.db.types.UtcDateTime(), nullable=False),
    sa.Column('acknowledged_at', caps_dash.db.types.UtcDateTime(), nullable=True),
    sa.Column('acknowledged_by_id', sa.Integer(), nullable=True),
    sa.Column('clock_suspect', sa.Boolean(), nullable=False),
    sa.CheckConstraint("alert_type IN ('camera_offline', 'overstay', 'disk_low', 'slot_overlap', 'clock_unsynced')", name=op.f('ck_alerts_alert_type_valid')),
    sa.CheckConstraint("severity IN ('info', 'warning', 'critical')", name=op.f('ck_alerts_severity_valid')),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], name=op.f('fk_alerts_acknowledged_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_clock_suspect'), ['clock_suspect'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_alerts_open_recent', ['acknowledged_at', 'created_at'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=24), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', caps_dash.db.types.UtcDateTime(), nullable=False),
    sa.Column('clock_suspect', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_clock_suspect'), ['clock_suspect'], unique=False)
        batch_op.create_index('ix_audit_logs_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_username'), ['username'], unique=False)

    op.create_table('parking_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('floor', sa.String(length=16), nullable=False),
    sa.Column('polygon_json', sa.JSON(), nullable=False),
    sa.Column('src_frame_width', sa.Integer(), nullable=False),
    sa.Column('src_frame_height', sa.Integer(), nullable=False),
    sa.Column('current_state', sa.String(length=16), nullable=False),
    sa.Column('state_since', caps_dash.db.types.UtcDateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', caps_dash.db.types.UtcDateTime(), nullable=False),
    sa.Column('updated_at', caps_dash.db.types.UtcDateTime(), nullable=False),
    sa.CheckConstraint("current_state IN ('UNKNOWN', 'FREE', 'OCCUPIED')", name=op.f('ck_parking_slots_state_valid')),
    sa.CheckConstraint('src_frame_height > 0', name=op.f('ck_parking_slots_src_height_positive')),
    sa.CheckConstraint('src_frame_width > 0', name=op.f('ck_parking_slots_src_width_positive')),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_parking_slots_camera_id_cameras'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parking_slots')),
    sa.UniqueConstraint('camera_id', 'code', name='code_unique_per_camera')
    )
    with op.batch_alter_table('parking_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parking_slots_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parking_slots_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_parking_slots_current_state'), ['current_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_parking_slots_floor'), ['floor'], unique=False)

    op.create_table('refresh_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('issued_at', caps_dash.db.types.UtcDateTime(), nullable=False),
    sa.Column('expires_at', caps_dash.db.types.UtcDateTime(), nullable=False),
    sa.Column('last_used_at', caps_dash.db.types.UtcDateTime(), nullable=True),
    sa.Column('revoked_at', caps_dash.db.types.UtcDateTime(), nullable=True),
    sa.Column('rotated_at', caps_dash.db.types.UtcDateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_sessions'))
    )
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_sessions_jti'), ['jti'], unique=True)
        batch_op.create_index('ix_refresh_sessions_user_active', ['user_id', 'revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('slot_state_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('camera_code', sa.String(length=16), nullable=False),
    sa.Column('slot_code', sa.String(length=16), nullable=False),
    sa.Column('floor', sa.String(length=16), nullable=False),
    sa.Column('previous_state', sa.String(length=16), nullable=False),
    sa.Column('new_state', sa.String(length=16), nullable=False),
    sa.Column('changed_at', caps_dash.db.types.UtcDateTime(), nullable=False),
    sa.Column('clock_suspect', sa.Boolean(), nullable=False),
    sa.CheckConstraint("new_state IN ('UNKNOWN', 'FREE', 'OCCUPIED')", name=op.f('ck_slot_state_history_new_state_valid')),
    sa.ForeignKeyConstraint(['slot_id'], ['parking_slots.id'], name=op.f('fk_slot_state_history_slot_id_parking_slots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_slot_state_history'))
    )
    with op.batch_alter_table('slot_state_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slot_state_history_camera_code'), ['camera_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_slot_state_history_clock_suspect'), ['clock_suspect'], unique=False)
        batch_op.create_index(batch_op.f('ix_slot_state_history_floor'), ['floor'], unique=False)
        batch_op.create_index(batch_op.f('ix_slot_state_history_slot_id'), ['slot_id'], unique=False)
        batch_op.create_index('ix_slot_state_history_slot_time', ['slot_id', 'changed_at'], unique=False)
        batch_op.create_index('ix_slot_state_history_time', ['changed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slot_state_history', schema=None) as batch_op:
        batch_op.drop_index('ix_slot_state_history_time')
        batch_op.drop_index('ix_slot_state_history_slot_time')
        batch_op.drop_index(batch_op.f('ix_slot_state_history_slot_id'))
        batch_op.drop_index(batch_op.f('ix_slot_state_history_floor'))
        batch_op.drop_index(batch_op.f('ix_slot_state_history_clock_suspect'))
        batch_op.drop_index(batch_op.f('ix_slot_state_history_camera_code'))

    op.drop_table('slot_state_history')
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_user_id'))
        batch_op.drop_index('ix_refresh_sessions_user_active')
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_jti'))

    op.drop_table('refresh_sessions')
    with op.batch_alter_table('parking_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parking_slots_floor'))
        batch_op.drop_index(batch_op.f('ix_parking_slots_current_state'))
        batch_op.drop_index(batch_op.f('ix_parking_slots_code'))
        batch_op.drop_index(batch_op.f('ix_parking_slots_camera_id'))

    op.drop_table('parking_slots')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_username'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_request_id'))
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index('ix_audit_logs_created')
        batch_op.drop_index(batch_op.f('ix_audit_logs_clock_suspect'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_alerts_open_recent')
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_clock_suspect'))
        batch_op.drop_index(batch_op.f('ix_alerts_alert_type'))

    op.drop_table('alerts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))

    op.drop_table('users')
    with op.batch_alter_table('hourly_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hourly_stats_scope_type'))
        batch_op.drop_index(batch_op.f('ix_hourly_stats_scope_key'))
        batch_op.drop_index(batch_op.f('ix_hourly_stats_hour_start'))
        batch_op.drop_index(batch_op.f('ix_hourly_stats_clock_suspect'))

    op.drop_table('hourly_stats')
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cameras_is_enabled'))
        batch_op.drop_index(batch_op.f('ix_cameras_floor'))
        batch_op.drop_index(batch_op.f('ix_cameras_code'))

    op.drop_table('cameras')
    # ### end Alembic commands ###
